//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_Кафедра.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("КП_Кафедра.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати.
        /// </summary>
        internal static string btnAddTeacher {
            get {
                return ResourceManager.GetString("btnAddTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Призначення.
        /// </summary>
        internal static string btnAssignments {
            get {
                return ResourceManager.GetString("btnAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деактивувати.
        /// </summary>
        internal static string btnDeactivateTeacher {
            get {
                return ResourceManager.GetString("btnDeactivateTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на              Головна сторінка.
        /// </summary>
        internal static string btnHead {
            get {
                return ResourceManager.GetString("btnHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантажити.
        /// </summary>
        internal static string btnLoad {
            get {
                return ResourceManager.GetString("btnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участь у проєктах.
        /// </summary>
        internal static string btnParticipation {
            get {
                return ResourceManager.GetString("btnParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проєкти.
        /// </summary>
        internal static string btnResearches {
            get {
                return ResourceManager.GetString("btnResearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на              Налаштування.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дисципліни.
        /// </summary>
        internal static string btnSubjects {
            get {
                return ResourceManager.GetString("btnSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Викладачі.
        /// </summary>
        internal static string btnTeachers {
            get {
                return ResourceManager.GetString("btnTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оновити.
        /// </summary>
        internal static string btnUpdateTeacher {
            get {
                return ResourceManager.GetString("btnUpdateTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string chkActive {
            get {
                return ResourceManager.GetString("chkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string column_assignment_id {
            get {
                return ResourceManager.GetString("column_assignment_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Електронна пошта.
        /// </summary>
        internal static string column_email {
            get {
                return ResourceManager.GetString("column_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПІБ.
        /// </summary>
        internal static string column_emp_full_name {
            get {
                return ResourceManager.GetString("column_emp_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата працевлаштування.
        /// </summary>
        internal static string column_emp_hire_date {
            get {
                return ResourceManager.GetString("column_emp_hire_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string column_emp_id {
            get {
                return ResourceManager.GetString("column_emp_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посада.
        /// </summary>
        internal static string column_emp_position {
            get {
                return ResourceManager.GetString("column_emp_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата завершення.
        /// </summary>
        internal static string column_end_date {
            get {
                return ResourceManager.GetString("column_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відпрацьовано годин.
        /// </summary>
        internal static string column_hours_taught {
            get {
                return ResourceManager.GetString("column_hours_taught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        internal static string column_phone_number {
            get {
                return ResourceManager.GetString("column_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на План годин.
        /// </summary>
        internal static string column_plan_hours {
            get {
                return ResourceManager.GetString("column_plan_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string column_research_id {
            get {
                return ResourceManager.GetString("column_research_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва проєкту.
        /// </summary>
        internal static string column_research_name {
            get {
                return ResourceManager.GetString("column_research_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Семестр.
        /// </summary>
        internal static string column_semester {
            get {
                return ResourceManager.GetString("column_semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата початку.
        /// </summary>
        internal static string column_start_date {
            get {
                return ResourceManager.GetString("column_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string column_status {
            get {
                return ResourceManager.GetString("column_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string column_subject_id {
            get {
                return ResourceManager.GetString("column_subject_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва предмету.
        /// </summary>
        internal static string column_subject_name {
            get {
                return ResourceManager.GetString("column_subject_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загальна кількість годин.
        /// </summary>
        internal static string column_total_hours {
            get {
                return ResourceManager.GetString("column_total_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип заняття.
        /// </summary>
        internal static string column_type_name {
            get {
                return ResourceManager.GetString("column_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мова застосунку:.
        /// </summary>
        internal static string lbLanguage {
            get {
                return ResourceManager.GetString("lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Електронна пошта.
        /// </summary>
        internal static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПІБ.
        /// </summary>
        internal static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        internal static string txtPhone {
            get {
                return ResourceManager.GetString("txtPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посада.
        /// </summary>
        internal static string txtPosition {
            get {
                return ResourceManager.GetString("txtPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть ім’я.
        /// </summary>
        internal static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
    }
}
